# Generated by Django 3.2.7 on 2023-05-03 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('description', models.TextField(verbose_name='описание')),
                ('telegram', models.URLField(verbose_name='telegram')),
                ('whatsapp', models.URLField(verbose_name='whatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('image_video', models.ImageField(upload_to='images1')),
                ('name_video', models.CharField(max_length=127)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='mainapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=127)),
                ('price', models.CharField(max_length=127)),
                ('type_work', models.CharField(max_length=127)),
                ('description', models.TextField(verbose_name='описание')),
                ('telegram', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=127)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='mainapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=127)),
                ('date', models.DateTimeField()),
                ('website', models.URLField()),
                ('registration', models.URLField()),
                ('description', models.TextField(verbose_name='описание1')),
                ('name', models.CharField(max_length=127)),
                ('image', models.ImageField(upload_to='images')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mainapp.company')),
            ],
        ),
    ]
